### ISSUE TITLE
[FR] - use latest JDK17 LTS

### ISSUE THREAD

**Issue by matiwinnetou** [adabox-aio/auth-server#1]
I saw project uses JDK15, which is not a LTS version, better to use LTS

**Comment by edridudi** [comment]
@matiwinnetou . Will do !
 Thank you for the input.

**Comment by edridudi** [comment]
Resolved in https://github.com/adabox-aio/auth-server/commit/975171f0727f4a9c5e5a1da26fdd75c500a1b717
